# Generated by Django 4.1.7 on 2023-05-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('permissions', models.SmallIntegerField(choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, verbose_name='认证')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='用户')),
            ],
        ),
    ]
